
input:
  input_path_base: '../'

prediction:
  prediction_filename: 'cnn'

closed_loop:
  target: [-0.5, 0.3]
  target_dimension: [1, 2]
  bin_size_ms: 50
  lr: 0.1
  num_trials: 500
  epsilon: 0.05
  
output:
  path: '../figure/'
  filename: 'performance_summary_test.png'